apiVersion: v1
kind: ReplicationController
metadata:
  name: replication
spec:
  replicas: 2
  selector:
    app: helloworld-pod
  template:
    metadata:
      name: helloworld-pod
      labels:
        app: helloworld-pod
    spec:
      containers:
        - name: helloworld
          image: 09036229746/enquire-node
          ports:
            - containerPort: 5000
              name:  sample-pod-port

---

kind: Service
apiVersion: v1
metadata:
  name:  helloworld-pod-service
spec:
  selector:
    app: helloworld-pod
  type:  NodePort
  ports:
  - name:  helloworld-pod-port
    port:  5000
    targetPort:  sample-pod-port