apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practice-app
  template:
    metadata:
      labels:
        app: practice-app
    spec:
      containers:
        - name: practice-app
          image: 09036229746/practice_app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 30
          ports:
            - containerPort: 3000
              name: app-port

---
kind: Service
apiVersion: v1
metadata:
  name: practice-app
spec:
  selector:
    app: practice-app
  type: NodePort
  ports:
    - port: 80
      targetPort: app-port
