apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practice-app
  template:
    metadata:
      labels:
        app: practice-app
    spec:
      containers:
        - image: 09036229746/practice_app:v2
          name: practice-app
          resources:
            limits:
              cpu: "250m"
              memory: "128M"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 30
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: practice-secret
                  key: message
            - name:  DB_URI
              value: mongodb://db-service
          ports:
            - containerPort: 3000
              name: practice-port

---

apiVersion: v1
kind: Service
metadata:
  name: practice-service
spec:
  selector:
    app: practice-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: practice-port

